# Form implementation generated from reading ui file 'Ui_Compra.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Compra(object):
    def setupUi(self, Ui_Compra):
        Ui_Compra.setObjectName("Ui_Compra")
        Ui_Compra.resize(1917, 981)
        Ui_Compra.setStyleSheet("QWidget{\n"
"background-color: rgb(251, 251, 254);\n"
"}\n"
"\n"
"QHBoxLayout{\n"
"background-color: black;\n"
"}\n"
"\n"
"QDateEdit{\n"
"font-family:\"Sans-serif\";\n"
"font-size:12px;\n"
"padding:10px 10px;\n"
"border-radius:20px;\n"
"border:2px solid rgb(228, 232, 235);\n"
"\n"
"}\n"
"QLabel{\n"
"font-family:\"Sans-serif\";\n"
"font-size:12px;\n"
"padding:5px;\n"
"\n"
"}\n"
"\n"
"QComboBox{\n"
"font-family:\"Sans-serif\";\n"
"font-size:12px;\n"
"padding:10px 10px;\n"
"border-radius:20px;\n"
"border:2px solid rgb(228, 232, 235);\n"
"}\n"
"\n"
"QLineEdit{\n"
"font-family:\"Sans-serif\";\n"
"font-size:12px;\n"
"padding:10px 10px;\n"
"border-radius:20px;\n"
"border:2px solid rgb(228, 232, 235);\n"
"}\n"
"\n"
"QPushButton{\n"
"font-family:\"Sans-serif\";\n"
"font-size:12px;\n"
"padding: 10px 10px;\n"
"border-radius: 25px;\n"
"border:2px solid rgb(228, 232, 235);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"border:2px solid rgb(118, 129, 249);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:2px solid rgb(118, 129, 249);\n"
"}")
        self.frame = QtWidgets.QFrame(parent=Ui_Compra)
        self.frame.setGeometry(QtCore.QRect(10, 70, 1521, 5))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 5))
        self.frame.setStyleSheet("background-color: rgb(118, 129, 249);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.grbInformacionGeneral = QtWidgets.QGroupBox(parent=Ui_Compra)
        self.grbInformacionGeneral.setGeometry(QtCore.QRect(10, 90, 731, 131))
        self.grbInformacionGeneral.setObjectName("grbInformacionGeneral")
        self.txtCodigo = QtWidgets.QLineEdit(parent=self.grbInformacionGeneral)
        self.txtCodigo.setEnabled(False)
        self.txtCodigo.setGeometry(QtCore.QRect(250, 70, 231, 40))
        self.txtCodigo.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.txtCodigo.setObjectName("txtCodigo")
        self.dtpFecha = QtWidgets.QDateEdit(parent=self.grbInformacionGeneral)
        self.dtpFecha.setGeometry(QtCore.QRect(490, 70, 231, 40))
        self.dtpFecha.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dtpFecha.setStyleSheet("QCalendarWidget QToolButton {\n"
"    color: black;\n"
"    background-color: #e6e6e6;\n"
"    border: none;\n"
"    margin: 5px;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QCalendarWidget QWidget#qt_calendar_navigationbar {\n"
"    background-color: #e6e6e6;\n"
"}\n"
"\n"
"QCalendarWidget QTableView {\n"
"    selection-background-color: #e6e6e6;\n"
"}\n"
"\n"
"\n"
"QCalendarWidget QMenu::item:selected {\n"
"    background-color: #e6e6e6; /* Color de fondo de la selección */\n"
"}")
        self.dtpFecha.setCalendarPopup(True)
        self.dtpFecha.setObjectName("dtpFecha")
        self.lblFecha = QtWidgets.QLabel(parent=self.grbInformacionGeneral)
        self.lblFecha.setGeometry(QtCore.QRect(490, 30, 48, 24))
        self.lblFecha.setObjectName("lblFecha")
        self.lblSucursal = QtWidgets.QLabel(parent=self.grbInformacionGeneral)
        self.lblSucursal.setGeometry(QtCore.QRect(10, 30, 60, 24))
        self.lblSucursal.setObjectName("lblSucursal")
        self.cmbSucursal = QtWidgets.QComboBox(parent=self.grbInformacionGeneral)
        self.cmbSucursal.setGeometry(QtCore.QRect(10, 70, 231, 40))
        self.cmbSucursal.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cmbSucursal.setObjectName("cmbSucursal")
        self.lblCodigo = QtWidgets.QLabel(parent=self.grbInformacionGeneral)
        self.lblCodigo.setGeometry(QtCore.QRect(250, 30, 53, 24))
        self.lblCodigo.setObjectName("lblCodigo")
        self.grbProveedor = QtWidgets.QGroupBox(parent=Ui_Compra)
        self.grbProveedor.setGeometry(QtCore.QRect(10, 220, 731, 181))
        self.grbProveedor.setObjectName("grbProveedor")
        self.lblRuc = QtWidgets.QLabel(parent=self.grbProveedor)
        self.lblRuc.setGeometry(QtCore.QRect(10, 20, 36, 24))
        self.lblRuc.setObjectName("lblRuc")
        self.lblRazonSocial = QtWidgets.QLabel(parent=self.grbProveedor)
        self.lblRazonSocial.setGeometry(QtCore.QRect(250, 20, 80, 24))
        self.lblRazonSocial.setObjectName("lblRazonSocial")
        self.lblTelefono = QtWidgets.QLabel(parent=self.grbProveedor)
        self.lblTelefono.setGeometry(QtCore.QRect(490, 20, 65, 24))
        self.lblTelefono.setObjectName("lblTelefono")
        self.txtRuc = QtWidgets.QLineEdit(parent=self.grbProveedor)
        self.txtRuc.setGeometry(QtCore.QRect(10, 50, 231, 40))
        self.txtRuc.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.txtRuc.setMaxLength(13)
        self.txtRuc.setObjectName("txtRuc")
        self.txtRazonSocial = QtWidgets.QLineEdit(parent=self.grbProveedor)
        self.txtRazonSocial.setGeometry(QtCore.QRect(250, 50, 231, 40))
        self.txtRazonSocial.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.txtRazonSocial.setObjectName("txtRazonSocial")
        self.txtTelefono = QtWidgets.QLineEdit(parent=self.grbProveedor)
        self.txtTelefono.setGeometry(QtCore.QRect(490, 50, 231, 40))
        self.txtTelefono.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.txtTelefono.setMaxLength(10)
        self.txtTelefono.setObjectName("txtTelefono")
        self.lblCiudad = QtWidgets.QLabel(parent=self.grbProveedor)
        self.lblCiudad.setGeometry(QtCore.QRect(250, 100, 51, 21))
        self.lblCiudad.setObjectName("lblCiudad")
        self.lblProvincia = QtWidgets.QLabel(parent=self.grbProveedor)
        self.lblProvincia.setGeometry(QtCore.QRect(10, 100, 61, 21))
        self.lblProvincia.setObjectName("lblProvincia")
        self.cmbProvincia = QtWidgets.QComboBox(parent=self.grbProveedor)
        self.cmbProvincia.setGeometry(QtCore.QRect(10, 130, 231, 40))
        self.cmbProvincia.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cmbProvincia.setEditable(True)
        self.cmbProvincia.setObjectName("cmbProvincia")
        self.cmbCiudad = QtWidgets.QComboBox(parent=self.grbProveedor)
        self.cmbCiudad.setGeometry(QtCore.QRect(250, 130, 221, 40))
        self.cmbCiudad.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cmbCiudad.setEditable(True)
        self.cmbCiudad.setObjectName("cmbCiudad")
        self.grbProducto = QtWidgets.QGroupBox(parent=Ui_Compra)
        self.grbProducto.setGeometry(QtCore.QRect(10, 410, 731, 341))
        self.grbProducto.setObjectName("grbProducto")
        self.lblNombreProducto = QtWidgets.QLabel(parent=self.grbProducto)
        self.lblNombreProducto.setGeometry(QtCore.QRect(12, 28, 113, 24))
        self.lblNombreProducto.setObjectName("lblNombreProducto")
        self.cmbCategorias = QtWidgets.QComboBox(parent=self.grbProducto)
        self.cmbCategorias.setGeometry(QtCore.QRect(490, 70, 191, 40))
        self.cmbCategorias.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cmbCategorias.setEditable(True)
        self.cmbCategorias.setObjectName("cmbCategorias")
        self.btnAgregarCategoria = QtWidgets.QPushButton(parent=self.grbProducto)
        self.btnAgregarCategoria.setGeometry(QtCore.QRect(680, 60, 50, 54))
        self.btnAgregarCategoria.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnAgregarCategoria.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./Assets/addButton.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnAgregarCategoria.setIcon(icon)
        self.btnAgregarCategoria.setIconSize(QtCore.QSize(30, 30))
        self.btnAgregarCategoria.setObjectName("btnAgregarCategoria")
        self.cmbNombre = QtWidgets.QComboBox(parent=self.grbProducto)
        self.cmbNombre.setGeometry(QtCore.QRect(12, 66, 231, 40))
        self.cmbNombre.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cmbNombre.setEditable(True)
        self.cmbNombre.setObjectName("cmbNombre")
        self.lblMarca = QtWidgets.QLabel(parent=self.grbProducto)
        self.lblMarca.setGeometry(QtCore.QRect(260, 30, 47, 24))
        self.lblMarca.setObjectName("lblMarca")
        self.cmbMarca = QtWidgets.QComboBox(parent=self.grbProducto)
        self.cmbMarca.setGeometry(QtCore.QRect(250, 70, 231, 40))
        self.cmbMarca.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cmbMarca.setEditable(True)
        self.cmbMarca.setObjectName("cmbMarca")
        self.lblCantidad = QtWidgets.QLabel(parent=self.grbProducto)
        self.lblCantidad.setGeometry(QtCore.QRect(12, 120, 63, 24))
        self.lblCantidad.setObjectName("lblCantidad")
        self.lblPrecioCompra = QtWidgets.QLabel(parent=self.grbProducto)
        self.lblPrecioCompra.setGeometry(QtCore.QRect(260, 120, 93, 24))
        self.lblPrecioCompra.setObjectName("lblPrecioCompra")
        self.txtPrecioCompra = QtWidgets.QLineEdit(parent=self.grbProducto)
        self.txtPrecioCompra.setGeometry(QtCore.QRect(250, 150, 231, 40))
        self.txtPrecioCompra.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.txtPrecioCompra.setObjectName("txtPrecioCompra")
        self.txtPrecioOficial = QtWidgets.QLineEdit(parent=self.grbProducto)
        self.txtPrecioOficial.setGeometry(QtCore.QRect(490, 150, 231, 40))
        self.txtPrecioOficial.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.txtPrecioOficial.setObjectName("txtPrecioOficial")
        self.txtCantidad = QtWidgets.QLineEdit(parent=self.grbProducto)
        self.txtCantidad.setGeometry(QtCore.QRect(12, 151, 231, 40))
        self.txtCantidad.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.txtCantidad.setObjectName("txtCantidad")
        self.lblPrecioOficial = QtWidgets.QLabel(parent=self.grbProducto)
        self.lblPrecioOficial.setGeometry(QtCore.QRect(480, 120, 82, 24))
        self.lblPrecioOficial.setObjectName("lblPrecioOficial")
        self.lblCategorias = QtWidgets.QLabel(parent=self.grbProducto)
        self.lblCategorias.setGeometry(QtCore.QRect(480, 30, 72, 24))
        self.lblCategorias.setObjectName("lblCategorias")
        self.btnIngresarProducto = QtWidgets.QPushButton(parent=self.grbProducto)
        self.btnIngresarProducto.setGeometry(QtCore.QRect(120, 240, 221, 38))
        self.btnIngresarProducto.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnIngresarProducto.setStyleSheet("border-radius: 15px;")
        self.btnIngresarProducto.setObjectName("btnIngresarProducto")
        self.btnLimpiarCampos = QtWidgets.QPushButton(parent=self.grbProducto)
        self.btnLimpiarCampos.setGeometry(QtCore.QRect(380, 240, 221, 38))
        self.btnLimpiarCampos.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnLimpiarCampos.setStyleSheet("border-radius: 15px;")
        self.btnLimpiarCampos.setObjectName("btnLimpiarCampos")
        self.btnIngresarCompra = QtWidgets.QPushButton(parent=Ui_Compra)
        self.btnIngresarCompra.setGeometry(QtCore.QRect(130, 790, 471, 38))
        self.btnIngresarCompra.setStyleSheet("border-radius: 15px;")
        self.btnIngresarCompra.setObjectName("btnIngresarCompra")
        self.layoutWidget = QtWidgets.QWidget(parent=Ui_Compra)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 11, 1521, 56))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAtras = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btnAtras.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./Assets/backButton.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnAtras.setIcon(icon1)
        self.btnAtras.setIconSize(QtCore.QSize(30, 30))
        self.btnAtras.setFlat(True)
        self.btnAtras.setObjectName("btnAtras")
        self.horizontalLayout.addWidget(self.btnAtras)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lblCompra = QtWidgets.QLabel(parent=self.layoutWidget)
        self.lblCompra.setObjectName("lblCompra")
        self.horizontalLayout.addWidget(self.lblCompra)
        self.layoutWidget1 = QtWidgets.QWidget(parent=Ui_Compra)
        self.layoutWidget1.setGeometry(QtCore.QRect(1250, 760, 281, 89))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblTotal = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.lblTotal.setObjectName("lblTotal")
        self.horizontalLayout_3.addWidget(self.lblTotal)
        self.txtTotal = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.txtTotal.setEnabled(False)
        self.txtTotal.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.txtTotal.setObjectName("txtTotal")
        self.horizontalLayout_3.addWidget(self.txtTotal)
        self.twCompra = QtWidgets.QTableWidget(parent=Ui_Compra)
        self.twCompra.setEnabled(True)
        self.twCompra.setGeometry(QtCore.QRect(760, 100, 771, 651))
        self.twCompra.setCornerButtonEnabled(True)
        self.twCompra.setObjectName("twCompra")
        self.twCompra.setColumnCount(0)
        self.twCompra.setRowCount(0)
        self.twCompra.horizontalHeader().setDefaultSectionSize(400)

        self.retranslateUi(Ui_Compra)
        QtCore.QMetaObject.connectSlotsByName(Ui_Compra)

    def retranslateUi(self, Ui_Compra):
        _translate = QtCore.QCoreApplication.translate
        Ui_Compra.setWindowTitle(_translate("Ui_Compra", "Compra"))
        self.grbInformacionGeneral.setTitle(_translate("Ui_Compra", "Información general"))
        self.lblFecha.setText(_translate("Ui_Compra", "Fecha"))
        self.lblSucursal.setText(_translate("Ui_Compra", "Sucursal"))
        self.lblCodigo.setText(_translate("Ui_Compra", "Código"))
        self.grbProveedor.setTitle(_translate("Ui_Compra", "Proveedor"))
        self.lblRuc.setText(_translate("Ui_Compra", "Ruc"))
        self.lblRazonSocial.setText(_translate("Ui_Compra", "Razón social"))
        self.lblTelefono.setText(_translate("Ui_Compra", "Teléfono"))
        self.txtRuc.setPlaceholderText(_translate("Ui_Compra", "Ingresar ruc"))
        self.txtRazonSocial.setPlaceholderText(_translate("Ui_Compra", "Ingresar razón social"))
        self.txtTelefono.setPlaceholderText(_translate("Ui_Compra", "Ingresar teléfono"))
        self.lblCiudad.setText(_translate("Ui_Compra", "Ciudad"))
        self.lblProvincia.setText(_translate("Ui_Compra", "Provincia"))
        self.grbProducto.setTitle(_translate("Ui_Compra", "Producto"))
        self.lblNombreProducto.setText(_translate("Ui_Compra", "Nombre producto"))
        self.lblMarca.setText(_translate("Ui_Compra", "Marca"))
        self.lblCantidad.setText(_translate("Ui_Compra", "Cantidad"))
        self.lblPrecioCompra.setText(_translate("Ui_Compra", "Precio compra"))
        self.txtPrecioCompra.setPlaceholderText(_translate("Ui_Compra", "Ingresar precio compra"))
        self.txtPrecioOficial.setPlaceholderText(_translate("Ui_Compra", "Ingresar precio oficial"))
        self.txtCantidad.setPlaceholderText(_translate("Ui_Compra", "Ingresar cantidad"))
        self.lblPrecioOficial.setText(_translate("Ui_Compra", "Precio oficial"))
        self.lblCategorias.setText(_translate("Ui_Compra", "Categorias"))
        self.btnIngresarProducto.setText(_translate("Ui_Compra", "Ingresar producto"))
        self.btnLimpiarCampos.setText(_translate("Ui_Compra", "Limpiar campos"))
        self.btnIngresarCompra.setText(_translate("Ui_Compra", "Ingresar compra"))
        self.lblCompra.setText(_translate("Ui_Compra", "Compra"))
        self.lblTotal.setText(_translate("Ui_Compra", "Total"))
