# Form implementation generated from reading ui file 'Ui_InformacionSupermercado.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_InformacionSupermercado(object):
    def setupUi(self, Ui_InformacionSupermercado):
        Ui_InformacionSupermercado.setObjectName("Ui_InformacionSupermercado")
        Ui_InformacionSupermercado.resize(924, 675)
        Ui_InformacionSupermercado.setStyleSheet("QWidget{\n"
"background-color: rgb(251, 251, 254);\n"
"}\n"
"\n"
"QHBoxLayout{\n"
"background-color: black;\n"
"}\n"
"\n"
"QLabel{\n"
"font-family:\"Sans-serif\";\n"
"font-size:12px;\n"
"padding:5px;\n"
"\n"
"}\n"
"\n"
"QComboBox{\n"
"font-family:\"Sans-serif\";\n"
"font-size:12px;\n"
"padding:10px 10px;\n"
"border-radius:20px;\n"
"border:2px solid rgb(228, 232, 235);\n"
"}\n"
"\n"
"QLineEdit{\n"
"font-family:\"Sans-serif\";\n"
"font-size:12px;\n"
"padding:10px 10px;\n"
"border-radius:20px;\n"
"border:2px solid rgb(228, 232, 235);\n"
"}\n"
"\n"
"QPushButton{\n"
"font-family:\"Sans-serif\";\n"
"font-size:12px;\n"
"padding: 10px 10px;\n"
"border-radius: 25px;\n"
"border:2px solid rgb(228, 232, 235);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"border:2px solid rgb(118, 129, 249);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:2px solid rgb(118, 129, 249);\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Ui_InformacionSupermercado)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAtras = QtWidgets.QPushButton(parent=Ui_InformacionSupermercado)
        self.btnAtras.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./Assets/backButton.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnAtras.setIcon(icon)
        self.btnAtras.setIconSize(QtCore.QSize(30, 30))
        self.btnAtras.setFlat(True)
        self.btnAtras.setObjectName("btnAtras")
        self.horizontalLayout.addWidget(self.btnAtras)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lblInformacionSupermercado = QtWidgets.QLabel(parent=Ui_InformacionSupermercado)
        self.lblInformacionSupermercado.setObjectName("lblInformacionSupermercado")
        self.horizontalLayout.addWidget(self.lblInformacionSupermercado)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem1, 10, 1, 1, 1)
        self.frame = QtWidgets.QFrame(parent=Ui_InformacionSupermercado)
        self.frame.setStyleSheet("background-color: rgb(118, 129, 249);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem2, 4, 0, 1, 1)
        self.txtRazonSocial = QtWidgets.QLineEdit(parent=Ui_InformacionSupermercado)
        self.txtRazonSocial.setObjectName("txtRazonSocial")
        self.gridLayout.addWidget(self.txtRazonSocial, 5, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem3, 4, 2, 1, 1)
        self.lblRazonSocial = QtWidgets.QLabel(parent=Ui_InformacionSupermercado)
        self.lblRazonSocial.setObjectName("lblRazonSocial")
        self.gridLayout.addWidget(self.lblRazonSocial, 4, 1, 1, 1)
        self.lblRuc = QtWidgets.QLabel(parent=Ui_InformacionSupermercado)
        self.lblRuc.setObjectName("lblRuc")
        self.gridLayout.addWidget(self.lblRuc, 2, 1, 1, 1)
        self.lblProvincia = QtWidgets.QLabel(parent=Ui_InformacionSupermercado)
        self.lblProvincia.setObjectName("lblProvincia")
        self.gridLayout.addWidget(self.lblProvincia, 6, 1, 1, 1)
        self.cmbProvincia = QtWidgets.QComboBox(parent=Ui_InformacionSupermercado)
        self.cmbProvincia.setEditable(True)
        self.cmbProvincia.setObjectName("cmbProvincia")
        self.gridLayout.addWidget(self.cmbProvincia, 7, 1, 1, 1)
        self.cmbCiudad = QtWidgets.QComboBox(parent=Ui_InformacionSupermercado)
        self.cmbCiudad.setEditable(True)
        self.cmbCiudad.setObjectName("cmbCiudad")
        self.gridLayout.addWidget(self.cmbCiudad, 9, 1, 1, 1)
        self.txtRuc = QtWidgets.QLineEdit(parent=Ui_InformacionSupermercado)
        self.txtRuc.setMaxLength(13)
        self.txtRuc.setObjectName("txtRuc")
        self.gridLayout.addWidget(self.txtRuc, 3, 1, 1, 1)
        self.lblCiudad = QtWidgets.QLabel(parent=Ui_InformacionSupermercado)
        self.lblCiudad.setObjectName("lblCiudad")
        self.gridLayout.addWidget(self.lblCiudad, 8, 1, 1, 1)
        self.btnGuardarCambios = QtWidgets.QPushButton(parent=Ui_InformacionSupermercado)
        self.btnGuardarCambios.setStyleSheet("border-radius: 15px;\n"
"")
        self.btnGuardarCambios.setIconSize(QtCore.QSize(30, 30))
        self.btnGuardarCambios.setFlat(False)
        self.btnGuardarCambios.setObjectName("btnGuardarCambios")
        self.gridLayout.addWidget(self.btnGuardarCambios, 11, 1, 1, 1)

        self.retranslateUi(Ui_InformacionSupermercado)
        QtCore.QMetaObject.connectSlotsByName(Ui_InformacionSupermercado)

    def retranslateUi(self, Ui_InformacionSupermercado):
        _translate = QtCore.QCoreApplication.translate
        Ui_InformacionSupermercado.setWindowTitle(_translate("Ui_InformacionSupermercado", "Información supermercado"))
        self.lblInformacionSupermercado.setText(_translate("Ui_InformacionSupermercado", "Información supermercado"))
        self.txtRazonSocial.setPlaceholderText(_translate("Ui_InformacionSupermercado", "Ingrese razón social"))
        self.lblRazonSocial.setText(_translate("Ui_InformacionSupermercado", "Razón social"))
        self.lblRuc.setText(_translate("Ui_InformacionSupermercado", "Ruc"))
        self.lblProvincia.setText(_translate("Ui_InformacionSupermercado", "Provincia"))
        self.txtRuc.setPlaceholderText(_translate("Ui_InformacionSupermercado", "Ingrese ruc"))
        self.lblCiudad.setText(_translate("Ui_InformacionSupermercado", "Ciudad"))
        self.btnGuardarCambios.setText(_translate("Ui_InformacionSupermercado", "Guardar cambios"))
