# Form implementation generated from reading ui file 'Ui_Listar.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Listar(object):
    def setupUi(self, Ui_Listar):
        Ui_Listar.setObjectName("Ui_Listar")
        Ui_Listar.resize(1075, 1061)
        Ui_Listar.setStyleSheet("QWidget{\n"
"background-color: rgb(251, 251, 254);\n"
"}\n"
"\n"
"QHBoxLayout{\n"
"background-color: black;\n"
"}\n"
"\n"
"QDateEdit{\n"
"font-family:\"Sans-serif\";\n"
"font-size:12px;\n"
"padding:10px 10px;\n"
"border-radius:20px;\n"
"border:2px solid rgb(228, 232, 235);\n"
"\n"
"}\n"
"QLabel{\n"
"font-family:\"Sans-serif\";\n"
"font-size:12px;\n"
"padding:5px;\n"
"\n"
"}\n"
"\n"
"QComboBox{\n"
"font-family:\"Sans-serif\";\n"
"font-size:12px;\n"
"padding:10px 10px;\n"
"border-radius:20px;\n"
"border:2px solid rgb(228, 232, 235);\n"
"}\n"
"\n"
"QLineEdit{\n"
"font-family:\"Sans-serif\";\n"
"font-size:12px;\n"
"padding:10px 10px;\n"
"border-radius:20px;\n"
"border:2px solid rgb(228, 232, 235);\n"
"}\n"
"\n"
"QPushButton{\n"
"font-family:\"Sans-serif\";\n"
"font-size:12px;\n"
"padding: 10px 10px;\n"
"border-radius: 25px;\n"
"border:2px solid rgb(228, 232, 235);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"border:2px solid rgb(118, 129, 249);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:2px solid rgb(118, 129, 249);\n"
"}")
        self.gridLayout_2 = QtWidgets.QGridLayout(Ui_Listar)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAtras = QtWidgets.QPushButton(parent=Ui_Listar)
        self.btnAtras.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./Assets/backButton.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnAtras.setIcon(icon)
        self.btnAtras.setIconSize(QtCore.QSize(30, 30))
        self.btnAtras.setFlat(True)
        self.btnAtras.setObjectName("btnAtras")
        self.horizontalLayout.addWidget(self.btnAtras)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lblVenta = QtWidgets.QLabel(parent=Ui_Listar)
        self.lblVenta.setObjectName("lblVenta")
        self.horizontalLayout.addWidget(self.lblVenta)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.btnListar = QtWidgets.QPushButton(parent=Ui_Listar)
        self.btnListar.setStyleSheet("border-radius: 15px;")
        self.btnListar.setObjectName("btnListar")
        self.gridLayout_2.addWidget(self.btnListar, 3, 0, 1, 1)
        self.frame = QtWidgets.QFrame(parent=Ui_Listar)
        self.frame.setStyleSheet("background-color: rgb(118, 129, 249);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.gridLayout_2.addWidget(self.frame, 1, 0, 1, 1)
        self.grbParametros = QtWidgets.QGroupBox(parent=Ui_Listar)
        self.grbParametros.setObjectName("grbParametros")
        self.gridLayout = QtWidgets.QGridLayout(self.grbParametros)
        self.gridLayout.setObjectName("gridLayout")
        self.cmbSucursal = QtWidgets.QComboBox(parent=self.grbParametros)
        self.cmbSucursal.setObjectName("cmbSucursal")
        self.gridLayout.addWidget(self.cmbSucursal, 1, 0, 1, 1)
        self.lblCompraVenta = QtWidgets.QLabel(parent=self.grbParametros)
        self.lblCompraVenta.setObjectName("lblCompraVenta")
        self.gridLayout.addWidget(self.lblCompraVenta, 0, 1, 1, 1)
        self.lblSucursal = QtWidgets.QLabel(parent=self.grbParametros)
        self.lblSucursal.setObjectName("lblSucursal")
        self.gridLayout.addWidget(self.lblSucursal, 0, 0, 1, 1)
        self.cmbCompraVenta = QtWidgets.QComboBox(parent=self.grbParametros)
        self.cmbCompraVenta.setObjectName("cmbCompraVenta")
        self.gridLayout.addWidget(self.cmbCompraVenta, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.grbParametros, 2, 0, 1, 1)
        self.twListado = QtWidgets.QTableWidget(parent=Ui_Listar)
        self.twListado.setObjectName("twListado")
        self.twListado.setColumnCount(0)
        self.twListado.setRowCount(0)
        self.twListado.horizontalHeader().setDefaultSectionSize(400)
        self.gridLayout_2.addWidget(self.twListado, 4, 0, 1, 1)

        self.retranslateUi(Ui_Listar)
        QtCore.QMetaObject.connectSlotsByName(Ui_Listar)

    def retranslateUi(self, Ui_Listar):
        _translate = QtCore.QCoreApplication.translate
        Ui_Listar.setWindowTitle(_translate("Ui_Listar", "Listar"))
        self.lblVenta.setText(_translate("Ui_Listar", "Listar"))
        self.btnListar.setText(_translate("Ui_Listar", "Listar"))
        self.grbParametros.setTitle(_translate("Ui_Listar", "Parámetros"))
        self.lblCompraVenta.setText(_translate("Ui_Listar", "Seleccion compra/venta"))
        self.lblSucursal.setText(_translate("Ui_Listar", "Seleccione sucursal"))
