# Form implementation generated from reading ui file 'Ui_Reportes.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Reportes(object):
    def setupUi(self, Ui_Reportes):
        Ui_Reportes.setObjectName("Ui_Reportes")
        Ui_Reportes.resize(967, 532)
        Ui_Reportes.setStyleSheet("QWidget{\n"
"background-color: rgb(251, 251, 254);\n"
"}\n"
"\n"
"QHBoxLayout{\n"
"background-color: black;\n"
"}\n"
"\n"
"QDateEdit{\n"
"font-family:\"Sans-serif\";\n"
"font-size:12px;\n"
"padding:10px 10px;\n"
"border-radius:20px;\n"
"border:2px solid rgb(228, 232, 235);\n"
"\n"
"}\n"
"QLabel{\n"
"font-family:\"Sans-serif\";\n"
"font-size:12px;\n"
"padding:5px;\n"
"\n"
"}\n"
"\n"
"QComboBox{\n"
"font-family:\"Sans-serif\";\n"
"font-size:12px;\n"
"padding:10px 10px;\n"
"border-radius:20px;\n"
"border:2px solid rgb(228, 232, 235);\n"
"}\n"
"\n"
"QLineEdit{\n"
"font-family:\"Sans-serif\";\n"
"font-size:12px;\n"
"padding:10px 10px;\n"
"border-radius:20px;\n"
"border:2px solid rgb(228, 232, 235);\n"
"}\n"
"\n"
"QPushButton{\n"
"font-family:\"Sans-serif\";\n"
"font-size:12px;\n"
"padding: 10px 10px;\n"
"border-radius: 25px;\n"
"border:2px solid rgb(228, 232, 235);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"border:2px solid rgb(118, 129, 249);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:2px solid rgb(118, 129, 249);\n"
"}")
        self.gridLayout_2 = QtWidgets.QGridLayout(Ui_Reportes)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAtras = QtWidgets.QPushButton(parent=Ui_Reportes)
        self.btnAtras.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./Assets/backButton.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnAtras.setIcon(icon)
        self.btnAtras.setIconSize(QtCore.QSize(30, 30))
        self.btnAtras.setFlat(True)
        self.btnAtras.setObjectName("btnAtras")
        self.horizontalLayout.addWidget(self.btnAtras)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lblReportes = QtWidgets.QLabel(parent=Ui_Reportes)
        self.lblReportes.setObjectName("lblReportes")
        self.horizontalLayout.addWidget(self.lblReportes)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(parent=Ui_Reportes)
        self.frame.setStyleSheet("background-color: rgb(118, 129, 249);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.gridLayout_2.addWidget(self.frame, 1, 0, 1, 1)
        self.grbParametros = QtWidgets.QGroupBox(parent=Ui_Reportes)
        self.grbParametros.setObjectName("grbParametros")
        self.gridLayout = QtWidgets.QGridLayout(self.grbParametros)
        self.gridLayout.setObjectName("gridLayout")
        self.dtpFechaInicio = QtWidgets.QDateEdit(parent=self.grbParametros)
        self.dtpFechaInicio.setStyleSheet("QCalendarWidget QToolButton {\n"
"    color: black;\n"
"    background-color: #e6e6e6;\n"
"    border: none;\n"
"    margin: 5px;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QCalendarWidget QWidget#qt_calendar_navigationbar {\n"
"    background-color: #e6e6e6;\n"
"}\n"
"\n"
"QCalendarWidget QTableView {\n"
"    selection-background-color: #e6e6e6;\n"
"}\n"
"\n"
"\n"
"QCalendarWidget QMenu::item:selected {\n"
"    background-color: #e6e6e6; /* Color de fondo de la selección */\n"
"}")
        self.dtpFechaInicio.setCalendarPopup(True)
        self.dtpFechaInicio.setObjectName("dtpFechaInicio")
        self.gridLayout.addWidget(self.dtpFechaInicio, 1, 1, 1, 1)
        self.lblFechaFin = QtWidgets.QLabel(parent=self.grbParametros)
        self.lblFechaFin.setObjectName("lblFechaFin")
        self.gridLayout.addWidget(self.lblFechaFin, 2, 1, 1, 1)
        self.lblSucursal = QtWidgets.QLabel(parent=self.grbParametros)
        self.lblSucursal.setObjectName("lblSucursal")
        self.gridLayout.addWidget(self.lblSucursal, 0, 0, 1, 1)
        self.lblFechaInicio = QtWidgets.QLabel(parent=self.grbParametros)
        self.lblFechaInicio.setObjectName("lblFechaInicio")
        self.gridLayout.addWidget(self.lblFechaInicio, 0, 1, 1, 1)
        self.cmbSucursal = QtWidgets.QComboBox(parent=self.grbParametros)
        self.cmbSucursal.setObjectName("cmbSucursal")
        self.gridLayout.addWidget(self.cmbSucursal, 1, 0, 1, 1)
        self.dtpFechaFin = QtWidgets.QDateEdit(parent=self.grbParametros)
        self.dtpFechaFin.setStyleSheet("QCalendarWidget QToolButton {\n"
"    color: black;\n"
"    background-color: #e6e6e6;\n"
"    border: none;\n"
"    margin: 5px;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QCalendarWidget QWidget#qt_calendar_navigationbar {\n"
"    background-color: #e6e6e6;\n"
"}\n"
"\n"
"QCalendarWidget QTableView {\n"
"    selection-background-color: #e6e6e6;\n"
"}\n"
"\n"
"\n"
"QCalendarWidget QMenu::item:selected {\n"
"    background-color: #e6e6e6; /* Color de fondo de la selección */\n"
"}")
        self.dtpFechaFin.setCalendarPopup(True)
        self.dtpFechaFin.setObjectName("dtpFechaFin")
        self.gridLayout.addWidget(self.dtpFechaFin, 3, 1, 1, 1)
        self.gridLayout_2.addWidget(self.grbParametros, 2, 0, 1, 1)
        self.btnObtenerReporte = QtWidgets.QPushButton(parent=Ui_Reportes)
        self.btnObtenerReporte.setStyleSheet("border-radius: 15px;")
        self.btnObtenerReporte.setObjectName("btnObtenerReporte")
        self.gridLayout_2.addWidget(self.btnObtenerReporte, 3, 0, 1, 1)
        self.twReporte = QtWidgets.QTableWidget(parent=Ui_Reportes)
        self.twReporte.setObjectName("twReporte")
        self.twReporte.setColumnCount(0)
        self.twReporte.setRowCount(0)
        self.twReporte.horizontalHeader().setDefaultSectionSize(400)
        self.gridLayout_2.addWidget(self.twReporte, 4, 0, 1, 1)

        self.retranslateUi(Ui_Reportes)
        QtCore.QMetaObject.connectSlotsByName(Ui_Reportes)

    def retranslateUi(self, Ui_Reportes):
        _translate = QtCore.QCoreApplication.translate
        Ui_Reportes.setWindowTitle(_translate("Ui_Reportes", "Reportes"))
        self.lblReportes.setText(_translate("Ui_Reportes", "Reportes"))
        self.grbParametros.setTitle(_translate("Ui_Reportes", "Parámetros"))
        self.lblFechaFin.setText(_translate("Ui_Reportes", "Seleccione fecha fin"))
        self.lblSucursal.setText(_translate("Ui_Reportes", "Seleccione sucursal"))
        self.lblFechaInicio.setText(_translate("Ui_Reportes", "Seleccione fecha inicio"))
        self.btnObtenerReporte.setText(_translate("Ui_Reportes", "Obtener reporte"))
