# Form implementation generated from reading ui file 'Ui_Supermercado.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Supermercado(object):
    def setupUi(self, Ui_Supermercado):
        Ui_Supermercado.setObjectName("Ui_Supermercado")
        Ui_Supermercado.resize(800, 600)
        Ui_Supermercado.setStyleSheet("QMainWindow{\n"
"    background-color: rgb(251, 251, 254);;\n"
"}\n"
"\n"
"/* QToolBar */\n"
"QToolBar{\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QToolButton{\n"
"    font-family: \"Sans-serif\";\n"
"    font-size: 12px;\n"
"    padding: 10px;\n"
"    margin: 5px;\n"
"    border-radius: 20px;\n"
"\n"
"}\n"
"\n"
"QToolButton:hover{\n"
"    background-color:rgb(118, 129, 249);\n"
"}\n"
"\n"
"/* QMenuBar */\n"
"QMenuBar{\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QMenuBar::item{\n"
"    font-family: \"Sans-serif\";\n"
"    font-size: 12px;\n"
"    padding: 5px 10px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QMenuBar::item:selected{\n"
"    background: #E4E8EB;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"/* QMenu */\n"
"QMenu{\n"
"    background-color: white;\n"
"    border: 2px solid rgb(228, 232, 235);\n"
"}\n"
"\n"
"QMenu::item{\n"
"    font-family: \"Sans-serif\";\n"
"    font-size: 12px;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QMenu::item:selected{\n"
"    background-color: rgb(118, 129, 249);\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=Ui_Supermercado)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.lblLogoSupermercado = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblLogoSupermercado.setText("")
        self.lblLogoSupermercado.setPixmap(QtGui.QPixmap("./Assets/supermercadoBackground.jpg"))
        self.lblLogoSupermercado.setScaledContents(True)
        self.lblLogoSupermercado.setObjectName("lblLogoSupermercado")
        self.gridLayout.addWidget(self.lblLogoSupermercado, 0, 0, 1, 1)
        Ui_Supermercado.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Ui_Supermercado)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 41))
        self.menubar.setObjectName("menubar")
        self.jmbMenu = QtWidgets.QMenu(parent=self.menubar)
        self.jmbMenu.setObjectName("jmbMenu")
        self.jmbSucursal = QtWidgets.QMenu(parent=self.menubar)
        self.jmbSucursal.setObjectName("jmbSucursal")
        self.jmbReportes = QtWidgets.QMenu(parent=self.menubar)
        self.jmbReportes.setObjectName("jmbReportes")
        Ui_Supermercado.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Ui_Supermercado)
        self.statusbar.setObjectName("statusbar")
        Ui_Supermercado.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(parent=Ui_Supermercado)
        self.toolBar.setObjectName("toolBar")
        Ui_Supermercado.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.jmbConfiguracion = QtGui.QAction(parent=Ui_Supermercado)
        self.jmbConfiguracion.setObjectName("jmbConfiguracion")
        self.jmbSalir = QtGui.QAction(parent=Ui_Supermercado)
        self.jmbSalir.setObjectName("jmbSalir")
        self.jmbIngresarSucursal = QtGui.QAction(parent=Ui_Supermercado)
        self.jmbIngresarSucursal.setObjectName("jmbIngresarSucursal")
        self.jmbModificarSucursal = QtGui.QAction(parent=Ui_Supermercado)
        self.jmbModificarSucursal.setObjectName("jmbModificarSucursal")
        self.jmbEliminarSucursal = QtGui.QAction(parent=Ui_Supermercado)
        self.jmbEliminarSucursal.setObjectName("jmbEliminarSucursal")
        self.jmbListarSucursal = QtGui.QAction(parent=Ui_Supermercado)
        self.jmbListarSucursal.setObjectName("jmbListarSucursal")
        self.jmbComprar = QtGui.QAction(parent=Ui_Supermercado)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./Assets/buyButton.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.jmbComprar.setIcon(icon)
        self.jmbComprar.setObjectName("jmbComprar")
        self.jmbVender = QtGui.QAction(parent=Ui_Supermercado)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./Assets/sellButton.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.jmbVender.setIcon(icon1)
        self.jmbVender.setObjectName("jmbVender")
        self.jmbListar = QtGui.QAction(parent=Ui_Supermercado)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./Assets/listButton.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.jmbListar.setIcon(icon2)
        self.jmbListar.setObjectName("jmbListar")
        self.jmbProductoMasDemanda = QtGui.QAction(parent=Ui_Supermercado)
        self.jmbProductoMasDemanda.setObjectName("jmbProductoMasDemanda")
        self.jmbProductoMenosDemanda = QtGui.QAction(parent=Ui_Supermercado)
        self.jmbProductoMenosDemanda.setObjectName("jmbProductoMenosDemanda")
        self.jmbBalance = QtGui.QAction(parent=Ui_Supermercado)
        self.jmbBalance.setObjectName("jmbBalance")
        self.jmbProductosMayorCantidadInventario = QtGui.QAction(parent=Ui_Supermercado)
        self.jmbProductosMayorCantidadInventario.setObjectName("jmbProductosMayorCantidadInventario")
        self.jmbClientesMasFrecuentes = QtGui.QAction(parent=Ui_Supermercado)
        self.jmbClientesMasFrecuentes.setObjectName("jmbClientesMasFrecuentes")
        self.jmbMenu.addAction(self.jmbConfiguracion)
        self.jmbMenu.addSeparator()
        self.jmbMenu.addAction(self.jmbSalir)
        self.jmbSucursal.addAction(self.jmbIngresarSucursal)
        self.jmbSucursal.addAction(self.jmbModificarSucursal)
        self.jmbSucursal.addAction(self.jmbEliminarSucursal)
        self.jmbSucursal.addAction(self.jmbListarSucursal)
        self.jmbReportes.addAction(self.jmbProductoMasDemanda)
        self.jmbReportes.addAction(self.jmbProductoMenosDemanda)
        self.jmbReportes.addAction(self.jmbBalance)
        self.jmbReportes.addAction(self.jmbProductosMayorCantidadInventario)
        self.jmbReportes.addAction(self.jmbClientesMasFrecuentes)
        self.menubar.addAction(self.jmbMenu.menuAction())
        self.menubar.addAction(self.jmbSucursal.menuAction())
        self.menubar.addAction(self.jmbReportes.menuAction())
        self.toolBar.addAction(self.jmbVender)
        self.toolBar.addAction(self.jmbComprar)
        self.toolBar.addAction(self.jmbListar)

        self.retranslateUi(Ui_Supermercado)
        QtCore.QMetaObject.connectSlotsByName(Ui_Supermercado)

    def retranslateUi(self, Ui_Supermercado):
        _translate = QtCore.QCoreApplication.translate
        Ui_Supermercado.setWindowTitle(_translate("Ui_Supermercado", "Supermercado"))
        self.jmbMenu.setTitle(_translate("Ui_Supermercado", "Menu"))
        self.jmbSucursal.setTitle(_translate("Ui_Supermercado", "Sucursal"))
        self.jmbReportes.setTitle(_translate("Ui_Supermercado", "Reportes"))
        self.toolBar.setWindowTitle(_translate("Ui_Supermercado", "toolBar"))
        self.jmbConfiguracion.setText(_translate("Ui_Supermercado", "Configuración"))
        self.jmbSalir.setText(_translate("Ui_Supermercado", "Salir"))
        self.jmbIngresarSucursal.setText(_translate("Ui_Supermercado", "Ingresar"))
        self.jmbModificarSucursal.setText(_translate("Ui_Supermercado", "Modificar"))
        self.jmbEliminarSucursal.setText(_translate("Ui_Supermercado", "Eliminar"))
        self.jmbListarSucursal.setText(_translate("Ui_Supermercado", "Listar"))
        self.jmbComprar.setText(_translate("Ui_Supermercado", "jmbComprar"))
        self.jmbComprar.setToolTip(_translate("Ui_Supermercado", "Comprar"))
        self.jmbVender.setText(_translate("Ui_Supermercado", "jmbVender"))
        self.jmbVender.setToolTip(_translate("Ui_Supermercado", "Vender"))
        self.jmbListar.setText(_translate("Ui_Supermercado", "jmbListar"))
        self.jmbListar.setToolTip(_translate("Ui_Supermercado", "Listar"))
        self.jmbProductoMasDemanda.setText(_translate("Ui_Supermercado", "Producto más demanda"))
        self.jmbProductoMenosDemanda.setText(_translate("Ui_Supermercado", "Producto menos demanda"))
        self.jmbBalance.setText(_translate("Ui_Supermercado", "Balance"))
        self.jmbProductosMayorCantidadInventario.setText(_translate("Ui_Supermercado", "Productos mayor cantidad en inventario"))
        self.jmbClientesMasFrecuentes.setText(_translate("Ui_Supermercado", "Clientes más frecuentes"))
