# Form implementation generated from reading ui file 'Ui_Venta.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Venta(object):
    def setupUi(self, Ui_Venta):
        Ui_Venta.setObjectName("Ui_Venta")
        Ui_Venta.resize(1958, 972)
        Ui_Venta.setStyleSheet("QWidget{\n"
"background-color: rgb(251, 251, 254);\n"
"}\n"
"\n"
"QHBoxLayout{\n"
"background-color: black;\n"
"}\n"
"\n"
"QDateEdit{\n"
"font-family:\"Sans-serif\";\n"
"font-size:12px;\n"
"padding:10px 10px;\n"
"border-radius:20px;\n"
"border:2px solid rgb(228, 232, 235);\n"
"\n"
"}\n"
"QLabel{\n"
"font-family:\"Sans-serif\";\n"
"font-size:12px;\n"
"padding:5px;\n"
"\n"
"}\n"
"\n"
"QComboBox{\n"
"font-family:\"Sans-serif\";\n"
"font-size:12px;\n"
"padding:10px 10px;\n"
"border-radius:20px;\n"
"border:2px solid rgb(228, 232, 235);\n"
"}\n"
"\n"
"QLineEdit{\n"
"font-family:\"Sans-serif\";\n"
"font-size:12px;\n"
"padding:10px 10px;\n"
"border-radius:20px;\n"
"border:2px solid rgb(228, 232, 235);\n"
"}\n"
"\n"
"QPushButton{\n"
"font-family:\"Sans-serif\";\n"
"font-size:12px;\n"
"padding: 10px 10px;\n"
"border-radius: 25px;\n"
"border:2px solid rgb(228, 232, 235);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"border:2px solid rgb(118, 129, 249);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:2px solid rgb(118, 129, 249);\n"
"}")
        self.grbCliente = QtWidgets.QGroupBox(parent=Ui_Venta)
        self.grbCliente.setGeometry(QtCore.QRect(10, 240, 731, 271))
        self.grbCliente.setObjectName("grbCliente")
        self.lblNombreCliente = QtWidgets.QLabel(parent=self.grbCliente)
        self.lblNombreCliente.setGeometry(QtCore.QRect(250, 30, 67, 27))
        self.lblNombreCliente.setObjectName("lblNombreCliente")
        self.lblCorreo = QtWidgets.QLabel(parent=self.grbCliente)
        self.lblCorreo.setGeometry(QtCore.QRect(10, 120, 60, 27))
        self.lblCorreo.setObjectName("lblCorreo")
        self.txtCedula = QtWidgets.QLineEdit(parent=self.grbCliente)
        self.txtCedula.setGeometry(QtCore.QRect(10, 60, 231, 43))
        self.txtCedula.setMaxLength(13)
        self.txtCedula.setObjectName("txtCedula")
        self.txtTelefono = QtWidgets.QLineEdit(parent=self.grbCliente)
        self.txtTelefono.setGeometry(QtCore.QRect(510, 60, 211, 43))
        self.txtTelefono.setMaxLength(10)
        self.txtTelefono.setObjectName("txtTelefono")
        self.lblTelefono = QtWidgets.QLabel(parent=self.grbCliente)
        self.lblTelefono.setGeometry(QtCore.QRect(510, 30, 70, 27))
        self.lblTelefono.setObjectName("lblTelefono")
        self.lblCedula = QtWidgets.QLabel(parent=self.grbCliente)
        self.lblCedula.setGeometry(QtCore.QRect(10, 30, 59, 27))
        self.lblCedula.setObjectName("lblCedula")
        self.txtNombreCliente = QtWidgets.QLineEdit(parent=self.grbCliente)
        self.txtNombreCliente.setGeometry(QtCore.QRect(250, 60, 251, 43))
        self.txtNombreCliente.setObjectName("txtNombreCliente")
        self.txtCorreo = QtWidgets.QLineEdit(parent=self.grbCliente)
        self.txtCorreo.setGeometry(QtCore.QRect(10, 150, 231, 43))
        self.txtCorreo.setObjectName("txtCorreo")
        self.lblDescuento = QtWidgets.QLabel(parent=self.grbCliente)
        self.lblDescuento.setGeometry(QtCore.QRect(10, 210, 84, 43))
        self.lblDescuento.setObjectName("lblDescuento")
        self.txtDescuento = QtWidgets.QLineEdit(parent=self.grbCliente)
        self.txtDescuento.setEnabled(False)
        self.txtDescuento.setGeometry(QtCore.QRect(240, 210, 261, 43))
        self.txtDescuento.setObjectName("txtDescuento")
        self.layoutWidget = QtWidgets.QWidget(parent=self.grbCliente)
        self.layoutWidget.setGeometry(QtCore.QRect(250, 150, 251, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lblTarjeta = QtWidgets.QLabel(parent=self.layoutWidget)
        self.lblTarjeta.setObjectName("lblTarjeta")
        self.horizontalLayout_4.addWidget(self.lblTarjeta)
        self.cbTarjeta = QtWidgets.QCheckBox(parent=self.layoutWidget)
        self.cbTarjeta.setText("")
        self.cbTarjeta.setObjectName("cbTarjeta")
        self.horizontalLayout_4.addWidget(self.cbTarjeta)
        self.grbInformacionGeneral = QtWidgets.QGroupBox(parent=Ui_Venta)
        self.grbInformacionGeneral.setGeometry(QtCore.QRect(10, 100, 731, 141))
        self.grbInformacionGeneral.setObjectName("grbInformacionGeneral")
        self.dtpFecha = QtWidgets.QDateEdit(parent=self.grbInformacionGeneral)
        self.dtpFecha.setGeometry(QtCore.QRect(510, 70, 211, 43))
        self.dtpFecha.setStyleSheet("QCalendarWidget QToolButton {\n"
"    color: black;\n"
"    background-color: #e6e6e6;\n"
"    border: none;\n"
"    margin: 5px;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QCalendarWidget QWidget#qt_calendar_navigationbar {\n"
"    background-color: #e6e6e6;\n"
"}\n"
"\n"
"QCalendarWidget QTableView {\n"
"    selection-background-color: #e6e6e6;\n"
"}\n"
"\n"
"\n"
"QCalendarWidget QMenu::item:selected {\n"
"    background-color: #e6e6e6; /* Color de fondo de la selección */\n"
"}")
        self.dtpFecha.setCalendarPopup(True)
        self.dtpFecha.setObjectName("dtpFecha")
        self.cmbSucursal = QtWidgets.QComboBox(parent=self.grbInformacionGeneral)
        self.cmbSucursal.setGeometry(QtCore.QRect(10, 70, 231, 43))
        self.cmbSucursal.setObjectName("cmbSucursal")
        self.lblCodigo = QtWidgets.QLabel(parent=self.grbInformacionGeneral)
        self.lblCodigo.setGeometry(QtCore.QRect(250, 30, 61, 27))
        self.lblCodigo.setObjectName("lblCodigo")
        self.txtCodigo = QtWidgets.QLineEdit(parent=self.grbInformacionGeneral)
        self.txtCodigo.setEnabled(False)
        self.txtCodigo.setGeometry(QtCore.QRect(250, 70, 251, 43))
        self.txtCodigo.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.txtCodigo.setStyleSheet("")
        self.txtCodigo.setObjectName("txtCodigo")
        self.lblFecha = QtWidgets.QLabel(parent=self.grbInformacionGeneral)
        self.lblFecha.setGeometry(QtCore.QRect(510, 30, 54, 27))
        self.lblFecha.setObjectName("lblFecha")
        self.lblSucursal = QtWidgets.QLabel(parent=self.grbInformacionGeneral)
        self.lblSucursal.setGeometry(QtCore.QRect(10, 30, 69, 27))
        self.lblSucursal.setObjectName("lblSucursal")
        self.frame = QtWidgets.QFrame(parent=Ui_Venta)
        self.frame.setGeometry(QtCore.QRect(11, 74, 1521, 5))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 5))
        self.frame.setStyleSheet("background-color: rgb(118, 129, 249);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.grbProducto = QtWidgets.QGroupBox(parent=Ui_Venta)
        self.grbProducto.setGeometry(QtCore.QRect(10, 520, 731, 231))
        self.grbProducto.setObjectName("grbProducto")
        self.lblCantidad = QtWidgets.QLabel(parent=self.grbProducto)
        self.lblCantidad.setGeometry(QtCore.QRect(260, 30, 72, 27))
        self.lblCantidad.setObjectName("lblCantidad")
        self.lblPrecioVenta = QtWidgets.QLabel(parent=self.grbProducto)
        self.lblPrecioVenta.setGeometry(QtCore.QRect(510, 30, 94, 27))
        self.lblPrecioVenta.setObjectName("lblPrecioVenta")
        self.txtCantidad = QtWidgets.QLineEdit(parent=self.grbProducto)
        self.txtCantidad.setGeometry(QtCore.QRect(260, 60, 241, 43))
        self.txtCantidad.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.txtCantidad.setObjectName("txtCantidad")
        self.lblNombreProducto = QtWidgets.QLabel(parent=self.grbProducto)
        self.lblNombreProducto.setGeometry(QtCore.QRect(12, 28, 128, 27))
        self.lblNombreProducto.setObjectName("lblNombreProducto")
        self.cmbNombreProducto = QtWidgets.QComboBox(parent=self.grbProducto)
        self.cmbNombreProducto.setGeometry(QtCore.QRect(10, 60, 241, 43))
        self.cmbNombreProducto.setObjectName("cmbNombreProducto")
        self.txtPrecioVenta = QtWidgets.QLineEdit(parent=self.grbProducto)
        self.txtPrecioVenta.setGeometry(QtCore.QRect(510, 60, 211, 43))
        self.txtPrecioVenta.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.txtPrecioVenta.setMaxLength(10)
        self.txtPrecioVenta.setObjectName("txtPrecioVenta")
        self.btnIngresarProducto = QtWidgets.QPushButton(parent=self.grbProducto)
        self.btnIngresarProducto.setGeometry(QtCore.QRect(160, 150, 421, 41))
        self.btnIngresarProducto.setStyleSheet("border-radius: 20px;")
        self.btnIngresarProducto.setObjectName("btnIngresarProducto")
        self.twVenta = QtWidgets.QTableWidget(parent=Ui_Venta)
        self.twVenta.setEnabled(True)
        self.twVenta.setGeometry(QtCore.QRect(760, 100, 771, 651))
        self.twVenta.setObjectName("twVenta")
        self.twVenta.setColumnCount(0)
        self.twVenta.setRowCount(0)
        self.twVenta.horizontalHeader().setDefaultSectionSize(400)
        self.btnIngresarVenta = QtWidgets.QPushButton(parent=Ui_Venta)
        self.btnIngresarVenta.setGeometry(QtCore.QRect(170, 790, 421, 41))
        self.btnIngresarVenta.setStyleSheet("border-radius: 20px;")
        self.btnIngresarVenta.setObjectName("btnIngresarVenta")
        self.layoutWidget1 = QtWidgets.QWidget(parent=Ui_Venta)
        self.layoutWidget1.setGeometry(QtCore.QRect(11, 11, 1521, 56))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAtras = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.btnAtras.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./Assets/backButton.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnAtras.setIcon(icon)
        self.btnAtras.setIconSize(QtCore.QSize(30, 30))
        self.btnAtras.setFlat(True)
        self.btnAtras.setObjectName("btnAtras")
        self.horizontalLayout.addWidget(self.btnAtras)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lblVenta = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.lblVenta.setObjectName("lblVenta")
        self.horizontalLayout.addWidget(self.lblVenta)
        self.layoutWidget2 = QtWidgets.QWidget(parent=Ui_Venta)
        self.layoutWidget2.setGeometry(QtCore.QRect(1200, 780, 331, 45))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblTotal = QtWidgets.QLabel(parent=self.layoutWidget2)
        self.lblTotal.setObjectName("lblTotal")
        self.horizontalLayout_3.addWidget(self.lblTotal)
        self.txtTotal = QtWidgets.QLineEdit(parent=self.layoutWidget2)
        self.txtTotal.setEnabled(False)
        self.txtTotal.setObjectName("txtTotal")
        self.horizontalLayout_3.addWidget(self.txtTotal)

        self.retranslateUi(Ui_Venta)
        QtCore.QMetaObject.connectSlotsByName(Ui_Venta)

    def retranslateUi(self, Ui_Venta):
        _translate = QtCore.QCoreApplication.translate
        Ui_Venta.setWindowTitle(_translate("Ui_Venta", "Venta"))
        self.grbCliente.setTitle(_translate("Ui_Venta", "Cliente"))
        self.lblNombreCliente.setText(_translate("Ui_Venta", "Nombre"))
        self.lblCorreo.setText(_translate("Ui_Venta", "Correo"))
        self.txtCedula.setPlaceholderText(_translate("Ui_Venta", "Ingresar cédula"))
        self.txtTelefono.setPlaceholderText(_translate("Ui_Venta", "Ingresar teléfono"))
        self.lblTelefono.setText(_translate("Ui_Venta", "Teléfono"))
        self.lblCedula.setText(_translate("Ui_Venta", "Cédula"))
        self.txtNombreCliente.setPlaceholderText(_translate("Ui_Venta", "Ingresar nombre"))
        self.txtCorreo.setPlaceholderText(_translate("Ui_Venta", "Ingresar correo"))
        self.lblDescuento.setText(_translate("Ui_Venta", "Descuento"))
        self.txtDescuento.setPlaceholderText(_translate("Ui_Venta", "Ingresar descuento"))
        self.lblTarjeta.setText(_translate("Ui_Venta", "Tarjeta"))
        self.grbInformacionGeneral.setTitle(_translate("Ui_Venta", "Información general"))
        self.lblCodigo.setText(_translate("Ui_Venta", "Código"))
        self.lblFecha.setText(_translate("Ui_Venta", "Fecha"))
        self.lblSucursal.setText(_translate("Ui_Venta", "Sucursal"))
        self.grbProducto.setTitle(_translate("Ui_Venta", "Producto"))
        self.lblCantidad.setText(_translate("Ui_Venta", "Cantidad"))
        self.lblPrecioVenta.setText(_translate("Ui_Venta", "Precio venta"))
        self.txtCantidad.setPlaceholderText(_translate("Ui_Venta", "Ingresar cantidad"))
        self.lblNombreProducto.setText(_translate("Ui_Venta", "Nombre producto"))
        self.txtPrecioVenta.setPlaceholderText(_translate("Ui_Venta", "Ingresar precio venta"))
        self.btnIngresarProducto.setText(_translate("Ui_Venta", "Ingresar producto"))
        self.btnIngresarVenta.setText(_translate("Ui_Venta", "Ingresar venta"))
        self.lblVenta.setText(_translate("Ui_Venta", "Venta"))
        self.lblTotal.setText(_translate("Ui_Venta", "Total"))
